### ISSUE TITLE
Exceptions thrown on/after May 31st, 2018 // Response did not indicate success: Status: 0 // TLS stuff

### ISSUE THREAD

**Issue by ishahrier** [nozzlegear/ShopifySharp#257]
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.ShopifyService.<>c__DisplayClass21_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.DefaultRequestExecutionPolicy.<Run>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.ShopifyService.<ExecuteRequestAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.RecurringChargeService.<GetAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ExicoShopifyCoreTools.Attributes.RequiresSubscription.OnAuthorization(AuthorizationContext filterContext) in C:\Users\ishahrier\Desktop\@Ishahrier\ExicoShopifyCoreV2\ExicoShopifyCoreV2\ExicoShopifyCoreTools\Attributes\RequiresSubscription.cs:line 63
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.ShopifyService.<>c__DisplayClass21_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.DefaultRequestExecutionPolicy.<Run>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.ShopifyService.<ExecuteRequestAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.RecurringChargeService.<GetAsync>d__2.MoveNext()<---

**Comment by pirke** [comment]
Been pulling my hair almost entire day cause of this.
Try adding this to Global.asax.cs 
System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

**Comment by ishahrier** [comment]
@pirke Dude if this works , i will parcel you beer!

**Comment by ishahrier** [comment]
@pirke  dude it worked!!!!!!! YOU ARE MY NEW HERO!!!!! How do i treat you!!!

**Comment by pirke** [comment]
👍 cool !! glad it helped
More info about what caused this here
https://medium.com/@kyle.gagnet/your-net-code-could-stop-working-in-june-afb35fbf29ca 
For some reason just updating to .net 4.7 didn't work for me

**Comment by olliehuynh** [comment]
You are a life saviour mate. Well done! Can give you 1000 thumb ups if I could

**Comment by Fashionepaul** [comment]
@pirke  I think this due to Shopify deprecating its support of TLS 1.0 and 1.1 on the 31st May 2018.

You would only need to use TLS 1.2:
`System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

https://ecommerce.shopify.com/c/api-announcements/t/shopify-is-deprecating-its-support-of-tls-1-0-and-1-1-517130

It probably should be added to the documentation.

**Comment by clement911** [comment]
Crap. This has broken our webhooks. 
Weirdly, we can call into the REST api OK.
Anyone else not receiving webhook requests?

**Comment by pirke** [comment]
Thanks @Fashionepaul
@clement911 we have issues with webhooks being delayed for almost a day and some fire ok
I escalated this to Shopify tehnical support but no response yet 
Not sure why Tls 1 and 1.1 depreciation would cause issue with webhooks ?

**Comment by clement911** [comment]
I know it's driving me crazy too!
Do you receive any webhooks at all? We haven't received any since the TLS1.2 release went live a few hours ago.

**Comment by clement911** [comment]
I started a post here https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/anyone-else-stopped-receiving-webhoooks-522356

**Comment by pirke** [comment]
Cool Let’s see what others say
I do receive some but with huge delay 
Normally I’d expect webhooks to expire after 19 retries according to documentation so I assumed issue is on Shopify’s side
It started a bit before tls change went live

**Comment by nozzlegear** [comment]
Yikes, the TLS thing is a nasty issue. I'm seeing it in my own apps too. Just curious, is this .NET Framework only, or has anybody seen this in their .NET Core/Standard apps?

**Comment by webchetan** [comment]
> Been pulling my hair almost entire day cause of this.
> Try adding this to Global.asax.cs
> System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

Thank you! This worked!!!!!!

**Comment by manojjagtap1981** [comment]
I have similar issue, but it is happening only when system is observing high load (i.e. data access layer has to wait more than 3-5 mins to return the data). I am running three processes from UI using parallel.Task (multi threaded), and then calling web api using HTTP client. 
Even if I add the solution provided in above article, I still facing socket exception. 

Please advise. 

Thank you
Manoj

**Comment by foxandrewj** [comment]
3 parallel processes all calling the API? You sure you aren't hitting the request limit?  You can easily hit request limit in a single thread if you don't add a delay between calls.

**Comment by manojjagtap1981** [comment]
All three calls are calling separate function in API. So the flow is like , 
1) Creating multiple threads for three different functions in MVC
2) Calling WebApi (using static http client & async/await) 
3) 2 functions are returning the data on UI but for 3rd one it is throwing an error.  

Even if I execute 3rd separately, it is failing. the DB is taking around 3-5 mins to return the data. 
I want web APi call to be remain active even after 5 mins and waiting for task to return the data. I have added time out more than 60 mins (in config, in code ) . nothing is working out. 
Please advise. 

Thanks
Manoj

**Comment by foxandrewj** [comment]
What DB? No call to Shopify's API should take 3-5 minutes. Is this your own DB? and it is taking 3-5 minutes to produce the results?

**Comment by manojjagtap1981** [comment]
yes, this application is little weird but cant do anything as business requirement is that way. 
We have Netezza DB with millions of data. The original requirement was to get a millions but now we are facing perf issue, we are working with 300 K . but for my testing purpose I kept the data to 100K. 
since we have three grids on single page and so pulling data for all three in multiple threads.

The Netezza DBA saying the timeout is not there on database and the query will execute everytime but it will take that much of time. 
so from application side , we need to keep that thread/call active to get that data. 

Thanks
Manoj

**Comment by foxandrewj** [comment]
So this has nothing to do with ShopifySharp package?  I would recommend post to stackexchange.com perhaps.

**Comment by manojjagtap1981** [comment]
got it. Thanks. 
The error looks similar to my issue, so put the question. Thanks though.
