### ISSUE TITLE
Tests are failing with "misused header name" exception

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#372]
This is currently blocking publish of any new versions to Nuget:

https://ci.appveyor.com/project/nozzlegear/shopifysharp/builds/25144046

**Comment by nozzlegear** [comment]
```
System.InvalidOperationException : Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
Stack Trace:
   at System.Net.Http.Headers.HttpHeaders.CheckHeaderName(String name)
   at System.Net.Http.Headers.HttpHeaders.GetValues(String name)
   at ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse) in C:\projects\shopifysharp\ShopifySharp\Services\ShopifyService.cs:line 238
   at ShopifySharp.ShopifyService.<>c__DisplayClass25_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext() in C:\projects\shopifysharp\ShopifySharp\Services\ShopifyService.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.DefaultRequestExecutionPolicy.<Run>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.ShopifyService.<ExecuteRequestAsync>d__25`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.CustomerAddressService.<CreateAsync>d__3.MoveNext() in C:\projects\shopifysharp\ShopifySharp\Services\CustomerAddress\CustomerAddressService.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.Tests.CustomerAddress_Tests_Fixture.<Create>d__16.MoveNext() in C:\projects\shopifysharp\ShopifySharp.Tests\CustomerAddress_Tests.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.Tests.CustomerAddress_Tests.<Gets_Addresses>d__6.MoveNext() in C:\projects\shopifysharp\ShopifySharp.Tests\CustomerAddress_Tests.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by dkershner6** [comment]
CustomerAddress? That smells like a Shopify change or something, I doubt we've touched it.

**Comment by nozzlegear** [comment]
That's just the test it happened to fail on, several others passed before this one failed. I think it has something to do with the change I made for #363, since that touches headers, but I haven't been able to investigate yet.

**Comment by dkershner6** [comment]
I don't see anything editing request headers in that pull request, just reading response headers.

**Comment by dkershner6** [comment]
I stand corrected, the method name does match on the Content-Type check.

**Comment by dkershner6** [comment]
Shopifyservice line 234:
response.Headers.GetValues("Content-Type")

Needs to be:
response.Content.Headers.ContentType

That's from memory, but close.

**Comment by nozzlegear** [comment]
That fixed it, thanks! Now that it's reading the response headers properly, it looks like the real error is this:

```
 ShopifySharp.ShopifyException : signature: has already been taken
Stack Trace:
   at ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse) in C:\projects\shopifysharp\ShopifySharp\Services\ShopifyService.cs:line 266
   at ShopifySharp.ShopifyService.<>c__DisplayClass25_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext() in C:\projects\shopifysharp\ShopifySharp\Services\ShopifyService.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.DefaultRequestExecutionPolicy.<Run>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.ShopifyService.<ExecuteRequestAsync>d__25`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.CustomerAddressService.<CreateAsync>d__3.MoveNext() in C:\projects\shopifysharp\ShopifySharp\Services\CustomerAddress\CustomerAddressService.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.Tests.CustomerAddress_Tests_Fixture.<Create>d__16.MoveNext() in C:\projects\shopifysharp\ShopifySharp.Tests\CustomerAddress_Tests.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.Tests.CustomerAddress_Tests.<Gets_Addresses>d__6.MoveNext() in C:\projects\shopifysharp\ShopifySharp.Tests\CustomerAddress_Tests.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

All other CustomerAddress tests are passing, it's just `ShopifySharp.Tests.CustomerAddress_Tests.Gets_Addresses` that fails.

**Comment by clement911** [comment]
Weird, it runs ok on my machine.

**Comment by nozzlegear** [comment]
I'm not sure what it even means by "signature". Maybe the addresses have to be unique?

**Comment by dkershner6** [comment]
Addresses do perhaps have to be minorly unique, and maybe the combo comparison is called 'signature'.

Delete all the customers on the shop, see what happens.

**Comment by nozzlegear** [comment]
Yep looks like they had to be unique, I fixed it by just using a random number in the street address.
