### ISSUE TITLE
CreateAsync Task Failed 

### ISSUE THREAD

**Issue by MuhammadTalha10** [nozzlegear/ShopifySharp#444]
Hi,
I am facing an issue in shopify fulfilment CreateAsync() it is only returning Task Failed 
I am passing the required id and fulfilment object to this function.
await fulfillmentService.CreateAsync(order.Id.Value, fulfillment);
I am using shopify sharp Version="4.21.4"

**Comment by nozzlegear** [comment]
Hey @MuhammadTalha10, could you please copy/paste the full exception message you're getting?

**Comment by MuhammadTalha10** [comment]
ShopifySharp.ShopifyException: Error: Not Found
   at ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse)
   at ShopifySharp.ShopifyService.<>c__DisplayClass25_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at ShopifySharp.DefaultRequestExecutionPolicy.Run[T](CloneableRequestMessage request, ExecuteRequestAsync`1 executeRequestAsync)
   at ShopifySharp.ShopifyService.ExecuteRequestAsync[T](RequestUri uri, HttpMethod method, HttpContent content, String rootElement)
   at ShopifySharp.FulfillmentService.CreateAsync(Int64 orderId, Fulfillment fulfillment)
   at HyvCallCourier.Manager.Helper.OrderHelper.GenerateCn(Order order, Shop shop, List`1 cities) in D:\Talha's Data\Al-Chemative\Hyv-Call-Courier-Public-ShopifyApp\HyvCallCourier\HyvCallCourier\Manager\Helper\OrderHelper.cs:line 155
   at HyvCallCourier.Manager.OrderManager.GenerateCn(Order order, Shop shop) in D:\Talha's Data\Al-Chemative\Hyv-Call-Courier-Public-ShopifyApp\HyvCallCourier\HyvCallCourier\Manager\OrderManager.cs:line 32
   at HyvCallCourier.Controllers.OrderController.GenerateCn(String orderId) in D:\Talha's Data\Al-Chemative\Hyv-Call-Courier-Public-ShopifyApp\HyvCallCourier\HyvCallCourier\Controllers\OrderController.cs:line 116

**Comment by MuhammadTalha10** [comment]
I think this is not the error I am getting it is not throwing any exception just return task failed I think

**Comment by MuhammadTalha10** [comment]
[40m[1m[33mwarn[39m[22m[49m: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'LastOrDefault()' could not be translated and will be evaluated locally.
ShopifySharp.ShopifyException: Error: Not Found
   at ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse)
   at ShopifySharp.ShopifyService.<>c__DisplayClass25_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at ShopifySharp.DefaultRequestExecutionPolicy.Run[T](CloneableRequestMessage request, ExecuteRequestAsync`1 executeRequestAsync)
   at ShopifySharp.ShopifyService.ExecuteRequestAsync[T](RequestUri uri, HttpMethod method, HttpContent content, String rootElement)
   at ShopifySharp.FulfillmentService.CreateAsync(Int64 orderId, Fulfillment fulfillment)
   at HyvCallCourier.Manager.Helper.OrderHelper.GenerateCn(Order order, Shop shop, List`1 cities) in D:\Talha's Data\Al-Chemative\Hyv-Call-Courier-Public-ShopifyApp\HyvCallCourier\HyvCallCourier\Manager\Helper\OrderHelper.cs:line 155
   at HyvCallCourier.Manager.OrderManager.GenerateCn(Order order, Shop shop) in D:\Talha's Data\Al-Chemative\Hyv-Call-Courier-Public-ShopifyApp\HyvCallCourier\HyvCallCourier\Manager\OrderManager.cs:line 32
   at HyvCallCourier.Controllers.OrderController.GenerateCn(String orderId) in D:\Talha's Data\Al-Chemative\Hyv-Call-Courier-Public-ShopifyApp\HyvCallCourier\HyvCallCourier\Controllers\OrderController.cs:line 116

**Comment by MuhammadTalha10** [comment]
ShopifySharp.ShopifyException: Error: Not Found
   at ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse)
   at ShopifySharp.ShopifyService.<>c__DisplayClass25_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at ShopifySharp.DefaultRequestExecutionPolicy.Run[T](CloneableRequestMessage request, ExecuteRequestAsync`1 executeRequestAsync)
   at ShopifySharp.ShopifyService.ExecuteRequestAsync[T](RequestUri uri, HttpMethod method, HttpContent content, String rootElement)
   at ShopifySharp.FulfillmentService.CreateAsync(Int64 orderId, Fulfillment fulfillment)
   at HyvCallCourier.Manager.Helper.OrderHelper.GenerateCn(Order order, Shop shop, List`1 cities) in D:\Talha's Data\Al-Chemative\Hyv-Call-Courier-Public-ShopifyApp\HyvCallCourier\HyvCallCourier\Manager\Helper\OrderHelper.cs:line 155
   at HyvCallCourier.Manager.OrderManager.GenerateCn(Order order, Shop shop) in D:\Talha's Data\Al-Chemative\Hyv-Call-Courier-Public-ShopifyApp\HyvCallCourier\HyvCallCourier\Manager\OrderManager.cs:line 32
   at HyvCallCourier.Controllers.OrderController.GenerateCn(String orderId) in D:\Talha's Data\Al-Chemative\Hyv-Call-Courier-Public-ShopifyApp\HyvCallCourier\HyvCallCourier\Controllers\OrderController.cs:line 116
The thread 'Worker Thread' (0x26f0) has exited with code 0 (0x0).
The thread 0x271e has exited with code 0 (0x0).
The thread 'Worker Thread' (0x2714) has exited with code 0 (0x0).
The thread 'Worker Thread' (0x26f8) has exited with code 0 (0x0).
The thread 0x271f has exited with code 0 (0x0).

**Comment by MuhammadTalha10** [comment]
![err](https://user-images.githubusercontent.com/56688362/73294089-f08a3000-4226-11ea-912e-357876c87221.PNG)

**Comment by MuhammadTalha10** [comment]
Any solution for this ? it is working fine for other shopify stores.

**Comment by MuhammadTalha10** [comment]
Any solution?

**Comment by nozzlegear** [comment]
From what I can tell, Shopify is returning a 404 Not Found error. Most likely that means the order you’re trying to create a fulfillment for doesn’t exist. It may have been deleted.

--
Josh Harms

**Comment by MuhammadTalha10** [comment]
This is happening on all orders of that store!
and orders do exist

**Comment by nozzlegear** [comment]
Unfortunately there’s not much more to go on. If Shopify is returning a 404 Not Found error, something somewhere must be missing. Can you catch the ShopifySharp exception and log the exception.RawBody property? That may provide more insight. 

--
Josh Harms

**Comment by MuhammadTalha10** [comment]
![err2](https://user-images.githubusercontent.com/56688362/73329747-94ec9080-4280-11ea-8e1d-d8a3843d55e5.PNG)

**Comment by nozzlegear** [comment]
So it does look to me like the order does not exist. When a fulfillment is being created, ShopifySharp takes the order ID and turns it into a URL that looks like `https://shop.myshopify.com/admin/api/api-version/{order-id-here}/fulfillments.json`. If that order ID isn't valid, Shopify would return a 404 Not Found error. 

I would test it out by trying to first look up the order with the Shopify API. If that returns the same Not Found error, then the order either doesn't exist or has been deleted:

```cs
var service = new OrderService(domain, token);

try
{
	var order = await service.GetAsync(orderIdHere);
	Console.WriteLine("Order exists, should be able to create fulfillment.");
}
catch (ShopifySharp.ShopifyException ex) when ((int) ex.StatusCode == 404)
{
    Console.WriteLine("Order does not exist. Order ID: " + orderIdHere);
}
```

**Comment by MuhammadTalha10** [comment]
this issue is being resolved you are right order is not found because the inventory locationId which is passed to this is disabled
