### ISSUE TITLE
Internal Server Error   at ShopifySharp.ShopifyService.CheckResponseExceptions

### ISSUE THREAD

**Issue by madushann** [nozzlegear/ShopifySharp#452]
We are having an issue recently in one of our apps which is using ProductService ListAsync API. It started giving exception as bellow, 

Error: Internal Server Error   at ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse)
   at ShopifySharp.ShopifyService.<>c__DisplayClass21_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at ShopifySharp.DefaultRequestExecutionPolicy.Run[T](CloneableRequestMessage request, ExecuteRequestAsync`1 executeRequestAsync)
   at ShopifySharp.ShopifyService.ExecuteRequestAsync[T](RequestUri uri, HttpMethod method, HttpContent content, String rootElement)
   at ShopifySharp.ProductService.ListAsync(ProductFilter options)

Could some one please help to understand the cause of this issue.

**Comment by clement911** [comment]
Internal error simply means that Shopify had a technical error internally.
It shouldn't last very long but if it does I'd recommend getting in touch with Shopify support.

**Comment by nozzlegear** [comment]
@madushann Let us know if you continue receiving this server error and I'll open the issue back up for investigation.
