### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by madushann** [nozzlegear/ShopifySharp#575]
We are getting an error while calling shopifysharp GraphService, we also use retry policy and it still keep throwing this error.
what could be the reason behind this?

We have tried the same cycle locally and it was working in production also it seems getting intermittently. But there are around 100 odd errors every 12 hours. 
 
An error occurred while sending the request.   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at ShopifySharp.ShopifyService.<>c__DisplayClass20_0.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at ShopifySharp.SmartRetryExecutionPolicy.Run[T](CloneableRequestMessage baseRequest, ExecuteRequestAsync`1 executeRequestAsync)
   at ShopifySharp.ShopifyService.ExecuteRequestAsync(RequestUri uri, HttpMethod method, HttpContent content)
   at ShopifySharp.GraphService.SendAsync(RequestUri req, HttpContent content)
   at ShopifySharp.GraphService.PostAsync(String body)
   at eFormed.GraphExtensions.VariantPriceGetAsync(GraphService graphService, Int64 variantId)
   at EFEnterprise.Shopify.PriceUpdate.RunAsync(MarketplaceChannel channel, ShopifyApiCall apiCall, Logger Log, Boolean secondary) in /app/EFEnterprise.Channels.Shopify/Shopify/APICalls/Price/PriceUpdate.cs:line 41
   at EFEnterprise.Shopify.ApiCalls.ProcessMessageAsync(MarketplaceChannel channel, ShopifyApiCall apiCall, Logger Log, Boolean secondary) in /app/EFEnterprise.Channels.Shopify/Shopify/APICalls/APICaller/ProcessMessageAsync.cs:line 60Unable to read data from the transport connection: Connection reset by peer.   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) Connection reset by peer

**Comment by madushann** [comment]
appreciate if you have any feedback on this
