### ISSUE TITLE
ShopifySharp.ShopifyRateLimitException even with SmartRetryExecutionPolicy

### ISSUE THREAD

**Issue by mavstuff** [nozzlegear/ShopifySharp#666]
hi there!

I have enabled the SmartRetryExecutionPolicy globally, but I am still getting the exceptions:

```
System.AggregateException: One or more errors occurred. ---> ShopifySharp.ShopifyRateLimitException: (429 Too Many Requests) product: Daily variant creation limit reached. Please try again later. See https://help.shopify.com/api/getting-started/api-call-limit for more information about rate limits and how to avoid them.
   at ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse)
   at ShopifySharp.ShopifyService.<>c__DisplayClass26_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.SmartRetryExecutionPolicy.<Run>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.ShopifyService.<ExecuteRequestAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShopifySharp.ProductService.<UpdateAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()

```

Any advice would be appreciated.

**Comment by clement911** [comment]
Are you running the program on multiple machines with the same token?
If so, you would have to ensure a single machine can use a given token.

**Comment by mavstuff** [comment]
> Are you running the program on multiple machines with the same token?
> If so, you would have to ensure a single machine can use a given token.
Hi!
I am not calling the app from multiple machines. 
Seems that the reason for the exception is that ShopifySharp only catches RateLimitException with the reason of empty LeakyBucket. But in my case there was a limit with Variants creation limit per day: (**Daily variant creation limit reached.** )
I have changed the **retryOnlyIfLeakyBucketFull** parameter for **SmartRetryExecutionPolicy** constructor to **false** and it is working ok now.

**Comment by clement911** [comment]
Can you please close if you fixed your issue?
